services:
  user:
    environment:
      # Configure your personal environment variables here
    volumes:
      - $HOME/.zshenv:$HOME/.zshenv
      - $HOME/.zsh:$HOME/.zsh
      - $HOME/.vim:$HOME/.vim
      - $HOME/.vimrc:$HOME/.vimrc
      - $HOME/.gitconfig:$HOME/.gitconfig
      - $HOME/.gitignore_global:$HOME/.gitignore_global
      - $HOME/.ssh:$HOME/.ssh
      # Mount your personal configurations here
