name: cd

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write # Required to create a release
  packages: write # Required to push docker image to registry

env:
  DOCKER_ENV_REGISTRY: ${{ vars.DOCKER_ENV_REGISTRY }}

jobs:
  tag_dev_image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_ENV_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Clone project
        uses: actions/checkout@v4

      - name: Pull dev image
        run: |
          RETRIES=3
          while [ $RETRIES -gt 0 ]; do
            if ./docker/env.sh pull ${{ github.sha }}; then
              exit 0
            else
              echo "Retrying in 1 minute"
              sleep 60
              RETRIES=$((RETRIES-1))
            fi
          done
          exit 1

      - name: Tag dev image with version
        run: |
          ./docker/env.sh tag ${{ github.ref_name }} ${{ github.sha }}
          ./docker/env.sh push ${{ github.ref_name }}
