name: cd

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  DOCKER_BUILDKIT: true
  DOCKER_ENV_REGISTRY: ghcr.io/logisparte

permissions:
  packages: write # Required to push docker image to registry

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_ENV_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Pull dev image
        run: ./docker/env.sh pull

      - name: Tag dev image with version
        run: |
          ./docker/env.sh tag ${{ github.ref_name }}
          ./docker/env.sh push ${{ github.ref_name }}
