name: ci-branch

on:
  pull_request:
    branches:
      - master

env:
  DOCKER_BUILDKIT: true
  DOCKER_ENV_REGISTRY: ghcr.io/logisparte

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_ENV_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Initialize docker env
        run: ./docker/env.sh init

      - name: Start docker env
        run: ./docker/env.sh up

      - name: Lint project
        run: ./docker/env.sh exec ./scripts/lint.sh all

      - name: Stop docker env
        run: ./docker/env.sh down
