name: ci_branch

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read # Required by actions/checkout
  packages: read # Required to pull docker image from registry

env:
  DOCKER_ENV_REGISTRY: ${{ vars.DOCKER_ENV_REGISTRY }}

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_ENV_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Clone project
        uses: actions/checkout@v4

      - name: Lint project
        run: ./docker/env.sh exec -- ./scripts/lint.sh

      - name: Wind down docker-env
        run: ./docker/env.sh compose down
