name: ci_master

on:
  push:
    branches:
      - master

permissions:
  contents: read # Required by actions/checkout
  packages: write # Required to push docker image to registry

env:
  DOCKER_ENV_REGISTRY: ${{ vars.DOCKER_ENV_REGISTRY }}

jobs:
  cache_dev_image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_ENV_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Clone project
        uses: actions/checkout@v4

      - name: Initialize docker env
        run: ./docker/env.sh init --platform linux/amd64,linux/arm64

      - name: Tag latest dev image
        run: |
          ./docker/env.sh tag ${{ github.sha }}
          ./docker/env.sh push ${{ github.sha }}
          ./docker/env.sh push
