name: ci_master

on:
  push:
    branches:
      - master

permissions:
  contents: read # Required by actions/checkout
  packages: write # Required to pull/push docker image from/to registry

env:
  DOCKER_ENV_REGISTRY: ${{ vars.DOCKER_ENV_REGISTRY }}
  DOCKER_ENV_BUILD_PLATFORMS: linux/arm64,linux/amd64

jobs:
  cache_dev_image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up multiarch docker builder
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          platforms: ${{ env.DOCKER_ENV_BUILD_PLATFORMS }}

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_ENV_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Clone project
        uses: actions/checkout@v4

      - name: Build dev env images
        run: ./docker/env.sh build

      - name: Tag dev env images with commit
        run: ./docker/env.sh tag ${{ github.sha }}

      - name: Push tagged dev env images
        run: ./docker/env.sh push
