name: ci_master

on:
  push:
    branches:
      - master

permissions:
  contents: read # Required by actions/checkout
  packages: write # Required to push docker image to registry

env:
  DOCKER_ENV_REGISTRY: ${{ vars.DOCKER_ENV_REGISTRY }}

jobs:
  cache_dev_image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_ENV_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up multiarch docker builder
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          platforms: linux/arm64,linux/amd64

      - name: Clone project
        uses: actions/checkout@v4

      - name: Build, tag and push docker env
        run: |
          ./docker/env.sh build \
            --platform linux/arm64 \
            --platform linux/amd64 \
            --tag latest \
            --tag ${{ github.sha }} \
            --push
